### ISSUE TITLE
Rancher node driver issue

### ISSUE THREAD

**Issue by hadifarnoud** [JonasProgrammer/docker-machine-driver-hetzner#43] opened 2020-03-20 22:00 UTC
Hello,

When I provision a node on Rancher, I get this error
```
Error setting machine configuration from flags provided: --hetzner-image and --hetzner-image-id are mutually exclusive; Timeout waiting for ssh key
--
```
What you think is wrong here?

I set `Download URL` as `https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/2.0.1/docker-machine-driver-hetzner_2.0.1_linux_amd64.tar.gz` and `custom UI URL` to `https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js`

**Comment by mxschmitt** [comment] 2020-03-20 22:23
Closed due duplicate of https://github.com/mxschmitt/ui-driver-hetzner/issues/82

**Closed by mxschmitt** 2020-03-20 22:23 UTC
